[package]
name = "tracing-filter"
version = "0.0.0-dev"
edition = "2021"
rust-version = "1.59"

autotests = false

[dependencies]
matchers = "0.1.0"
miette = "4.2.1"
once_cell = "1.10.0"
regex = "1.5.5"
smallvec = { version = "1.8.0", optional = true }
smartstring = "1.0.1"
sorted-vec = "0.7.0"
thiserror = "1.0.30"
thread_local = "1.1.4"

[dependencies.tracing]
version = "0.2.0"
git = "https://github.com/tokio-rs/tracing"
default-features = false
features = ["std"]

[dependencies.tracing-core]
version = "0.2.0"
git = "https://github.com/tokio-rs/tracing"
default-features = false
features = ["std"]

[dependencies.tracing-subscriber]
version = "0.3.0"
git = "https://github.com/tokio-rs/tracing"
default-features = false
features = ["std"]

[dev-dependencies]
insta = { version = "1.13.0", features = ["glob"] }
miette = { version = "4.2.1", features = ["fancy"] }

[dev-dependencies.tracing-mock]
version = "0.2.0"
git = "https://github.com/tokio-rs/tracing"
default-features = false

[[test]]
name = "lib"
