name: CI
on:
  push: # necessary for cache sharing
    branches:
      - v0.1
      - v0.2
  pull_request:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: short

jobs:
  style:
    name: Check style
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          toolchain: nightly-2022-07-01
          components: clippy, rustfmt
      - name: Setup cache
        uses: Swatinem/rust-cache@v2
      - name: cargo clippy
        run: cargo clippy --all-features --all-targets -- -Dwarnings
      - name: cargo fmt
        run: cargo fmt -- --check

  tests-nix:
    name: Run tests (ubuntu-latest)
    uses: ./.github/workflows/run-tests.yaml
    with:
      os: ubuntu-latest

  tests-win:
    name: Run tests (windows-latest)
    needs: tests-nix
    uses: ./.github/workflows/run-tests.yaml
    with:
      os: windows-latest

  tests-mac:
    name: Run tests (macOS-latest)
    needs: tests-nix
    uses: ./.github/workflows/run-tests.yaml
    with:
      os: macOS-latest

  tests-wasi:
    name: Run tests (wasi)
    runs-on: ubuntu-latest
    needs: tests-nix
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          targets: wasm32-wasi
      - name: Setup cache
        uses: Swatinem/rust-cache@v1
      - name: Install wasmtime
        uses: taiki-e/install-action@wasmtime
      - name: Refresh sh profile
        run: source ~/.profile
      - name: Install cargo-wasi
        run: cargo install cargo-wasi
      - name: Build tests
        run: cargo wasi test --all-features --all-targets --no-run
      - name: Run tests
        run: cargo wasi test --all-features --all-targets -- --nocapture

  features:
    name: Check feature powerset
    runs-on: ubuntu-latest
    needs: tests-nix
    env:
      CARGO_INCREMENTAL: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Setup cache
        uses: Swatinem/rust-cache@v1
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: Check feature powerset
        run: cargo hack check --feature-powerset --optional-deps --exclude-all-features --keep-going --lib --tests

  msrv:
    name: Check supported versions
    runs-on: ubuntu-latest
    needs: tests-nix
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: Check all versions
        run: cargo hack check --version-range .. --lib --all-features
