# A little paranoia, but not excessive

name: CI
on:
  push: # necessary for cache sharing
    branches: [v0.1]
  pull_request:

env:
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: short

jobs:
  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    env:
      RUST_NIGHTLY_PIN: nightly-2022-07-01 # upgrade this regularly
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust ${{env.RUST_NIGHTLY_PIN}}
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: ${{env.RUST_NIGHTLY_PIN}}
          components: rustfmt
      - name: cargo fmt
        run: cargo fmt -- --check

  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          kind: check
      - name: cargo check
        run: cargo check --all-features --all-targets

  clippy:
    name: cargo clippy
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          kind: check
          components: clippy
      - name: cargo clippy
        run: cargo clippy --all-features --all-targets -- -Dwarnings

  test:
    name: cargo test
    needs: check
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        id: setup
        with:
          kind: build
          tools: nextest
      - name: Build tests
        run: cargo test --all-features --all-targets --no-run
      - name: Run tests
        run: cargo nextest run -P ci --all-features --all-targets --no-fail-fast
      - name: Report tests
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: junit-${{runner.os}}
          path: target/nextest/ci/junit.xml
      - name: Run doctests
        run: cargo test --all-features --doc

  wasi:
    name: cargo wasi test
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        id: setup
        with:
          kind: wasi-build
          tools: wasmtime,cargo-wasi
      - name: Refresh sh profile
        run: source ~/.profile
      - name: Build tests
        run: cargo wasi test --all-features --all-targets --no-run
      - name: Run tests
        run: cargo wasi test --all-features --all-targets --no-fail-fast

  hack:
    name: cargo hack check --feature-powerset
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        id: setup
        with:
          kind: check
      - name: Check feature powerset
        run: cargo hack check --feature-powerset --optional-deps --exclude-all-features --keep-going --lib --tests

  msrv:
    name: cargo msrv verify
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        id: setup
        with:
          kind: msrv
          tools: cargo-msrv
      - name: Install cargo-msrv
        uses: taiki-e/install-action@v1
        with:
          tool: cargo-msrv
      - name: Check msrv
        run: cargo msrv verify
