on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  checks:
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [Windows, Linux, macOS]
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          name: junit-${{ matrix.os }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
      - name: Make checks
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{github.event.workflow_run.head.sha}}
          report_paths: junit.xml
          check_name: cargo test (${{matrix.os}})
          check_title_template: "{{SUITE_NAME}}::{{TEST_NAME}}"
