on:
  workflow_run:
    branches: [v0.1]
    workflows: [CI]
    types:
      - completed

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Make checks
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{github.event.workflow_run.head.sha}}
          report_paths: junit-${{matrix.os}}/junit.xml
          check_name: cargo test (${{matrix.os}})
          check_title_template: "{{SUITE_NAME}}::{{TEST_NAME}}"
