on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          name: junit-${{ runner.os }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
      - name: Make checks
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{github.event.workflow_run.head.sha}}
          report_paths: junit.xml
          check_name: cargo test (${{matrix.os}})
          check_title_template: "{{SUITE_NAME}}::{{TEST_NAME}}"
