on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: short

jobs:
  tests:
    name: Run tests
    runs-on: ${{ inputs.os }}
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Setup cache
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest
      - name: Build tests
        run: cargo test --all-features --all-targets --no-run
      - name: Run tests
        run: cargo nextest run -P ci --all-features --all-targets --no-fail-fast
      - name: Report tests
        if: ${{ always() }}
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: target/nextest/ci/junit.xml
          check_name: cargo test (ubuntu-latest)
          check_title_template: "{{SUITE_NAME}}::{{TEST_NAME}}"
      - name: Run doctests
        run: cargo test --all-features --doc
