name: rustdoc
on:
  push:
    branches:
      - master

jobs:
  cargo-doc:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.0

      - name: Install beta toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: beta
          profile: minimal
          override: true

      - name: Build docs
        uses: actions-rs/cargo@v1.0.3
        with:
          command: doc
          args: --no-deps

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ github.token }}
          publish_dir: ./target/doc
          force_orphan: true
